name: 🚀 Deploy to Remote Server

on:
  workflow_dispatch:
    inputs:
      instance-id:
        description: "🖥️ Remote Server Instance Id (Required)"
        required: true
      docker-image-version:
        description: "🏷️ Docker image version (DEFAULT latest)"
        required: true
        default: "latest"

jobs:
  pull-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Extract secrets and set up SSH
        uses: ./.github/workflows/helpers/extract-secrets.yml
        with:
          instance-id: ${{ inputs.instance-id }}

      # Step 3: Deploy on Remote Server
      - name: Deploy on Remote Server
        run: |
          # Ensure SSH key is available
          mkdir -p ~/.ssh
          echo "$REMOTE_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$REMOTE_SERVER_IP" >> ~/.ssh/known_hosts

          # SSH into the remote server to deploy
          ssh -T -i ~/.ssh/id_rsa "$REMOTE_SERVER_USER"@"$REMOTE_SERVER_IP" << EOF
          # Disable 'set -e' for more control
          set +e

          echo "Logging into Docker..."
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          echo "Pulling Docker image..."
          docker pull "${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.event.inputs.docker-image-version }}"

          echo "Stopping existing container (if any)..."
          docker stop "${{ inputs.instance-id }}" || true
          docker rm "${{ inputs.instance-id }}" || true

          echo "Starting new Docker container..."
          docker run -d \
            --name "${{ inputs.instance-id }}" \
            -p "$REMOTE_PORT:7210/tcp" \
            -p "$REMOTE_PORT:7210/udp" \
            -e BL_SRV_TOKEN=$BL_SRV_TOKEN \
            -e BL_SRV_CONFIG=$SERVER_CFG_FILE \
            "${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ inputs.docker-image-version }}"

          echo "Checking running containers..."
          docker ps

          echo "Deployment completed successfully."
          EOF
