name: 🚀 Deploy to Remote Server

on:
  workflow_dispatch:
    inputs:
      configuration-id:
        description: "♻️ Environment Configuration Id"
        required: true
      docker-image-version:
        description: "🏷️ Docker image version (DEFAULT latest)"
        required: true
        default: "latest"

jobs:
  pull-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.configuration-id }}

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IPV4 }} >> ~/.ssh/known_hosts

    - name: Deploy on Remote Server
      run: |
        ssh -T -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IPV4 }} << EOF
        # Disable 'set -e' for more control
        set +e
        
        echo "Logging into Docker..."
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
        echo "Pulling Docker image..."
        docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ inputs.docker-image-version }}
        
        echo "Stopping existing container (if any)..."
        docker stop ${{ inputs.configuration-id }} || true
        docker rm ${{ inputs.configuration-id }} || true
        
        echo "Starting new Docker container..."

        docker run -d --name ${{ inputs.configuration-id }} \
          -e TW_TOKEN=${{ secrets.TW_TOKEN }} \
          -e MODULES=${{ env.MODULES }} \
          -e TICK_RATE=${{ env.TICK_RATE }} \
          -p 7210:7210/tcp \
          -p 7210:7210/udp \
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ inputs.docker-image-version }}

        echo "Checking running containers..."
        docker ps
        
        echo "Deployment completed successfully."
        EOF