name: 🚀 Deploy to Remote Server

on:
  workflow_dispatch:
    inputs:
      configuration-id:
        description: "♻️ Environment Configuration Id"
        required: true
      docker-image-version:
        description: "🏷️ Docker image version"
        required: true
        default: "latest"
      server-cfg:
        description: "⚙️ Server Configuration Path"
        required: true 
        default: "Native/server.txt"
      modules-str:
        description: "📦 Modules Startup Command"
        required: true
        default: "_MODULES_*Native*Multiplayer*_MODULES_"
      tick-rate:
        description: "🕔 Tickrate"
        required: true
        type: number
        default: 60

jobs:
  pull-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.configuration-id }}

    steps:
    - name: Set up SSH
      run: |
        chmod +x ./scripts/ssh-prepare.sh
        ./scripts/ssh-prepare.sh

    - name: Deploy on Remote Server
      run: |
        chmod +x ./scripts/deploy-instance.sh
        ./scripts/deploy-instance.sh