name: 🕹️ Instance actions on Remote Server

on:
    workflow_dispatch:
      inputs:
        instance-id:
          description: "🖥️ Remote Server Instance Id (Required)"
          required: true
        instance-action:
          description: "🎬 Remote Server Action for Server Instance"
          type: choice
          options:
            - START
            - STOP
            - RESTART
            - DELETE

jobs:
  pull-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Extract secrets and set up SSH
        uses: ./.github/workflows/helpers/extract-secrets.yml
        with:
          instance-id: ${{ github.event.inputs.instance-id }}