name: Stop Instance on Remote Server

on:
    workflow_dispatch:
      inputs:
        instance-id:
          description: "Remote Server Instance Id"
          required: true

jobs:
  pull-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Extract secrets and set up SSH
        uses: ./.github/workflows/helpers/extract-secrets.yml
        with:
          instance-id: ${{ github.event.inputs.instance-id }}